apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxmyown
  name: nginxmyown
spec:
  containers:
  - image: nginx:1.14.2
    name: nginxmyown
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "eagle5"
    effect: "NoSchedule"
status: {}
