apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxnormal
  name: nginxnormal
spec:
  containers:
  - image: nginx:1.14.2
    name: nginxnormal
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
