apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-deployment
  labels:
    app: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: testing
        image: osagiefe/testingimage:latest
        ports:
        - containerPort: 5007